"""ViralOps Engine â€” Data Models"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional


class PublishMode(str, Enum):
    DRAFT = "draft"
    REVIEW = "review"
    QUEUE = "queue"
    AUTO = "auto"


class RiskLevel(str, Enum):
    LOW = "low"         # 0-3: auto-execute, 1 reviewer
    MEDIUM = "medium"   # 4-7: explicit approval, staging test
    HIGH = "high"       # 8-12: multi-stakeholder, phased rollout


class ContentType(str, Enum):
    ORIGINAL = "original"
    REPURPOSED = "repurposed"
    CURATED = "curated"
    REPOST = "repost"


class KillSwitchAction(str, Enum):
    STOP_PLATFORM = "STOP_PLATFORM"
    STOP_ALL = "STOP_ALL"
    STOP_REVIEW = "STOP_REVIEW"
    REDUCE_FREQUENCY = "REDUCE_FREQUENCY"
    DOWNGRADE_MODEL = "DOWNGRADE_MODEL"


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Content Pack Models
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

@dataclass
class HashtagMatrix:
    """5-Layer Hashtag Matrix"""
    niche: list[str] = field(default_factory=list)          # Layer 1: Niche-specific (1-2)
    trending: list[str] = field(default_factory=list)       # Layer 2: High-volume (1-2)
    community: list[str] = field(default_factory=list)      # Layer 3: Community/lifestyle (1)
    location_seasonal: list[str] = field(default_factory=list)  # Layer 4: Location/seasonal (1)
    viral_hook: list[str] = field(default_factory=list)     # Layer 5: Viral/hook (1)

    def all_hashtags(self) -> list[str]:
        return (
            self.niche
            + self.trending
            + self.community
            + self.location_seasonal
            + self.viral_hook
        )

    def top_n(self, n: int = 5) -> list[str]:
        """Return top N hashtags (YouTube = 3-5, TikTok = 5-8, IG = up to 30)"""
        all_tags = self.all_hashtags()
        return all_tags[:n]


@dataclass
class PlatformContent:
    """Content adapted for a specific platform"""
    platform: str
    title: str
    caption: str
    hashtags: list[str]
    media_urls: list[str] = field(default_factory=list)
    media_alt_text: list[str] = field(default_factory=list)
    video_ratio: str = "9:16"
    char_count: int = 0
    is_truncated: bool = False
    truncation_part: int = 1
    truncation_total: int = 1


@dataclass
class ContentPack:
    """Complete content pack generated by Content Factory"""
    id: str
    niche_id: str
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Content
    title: str = ""
    long_content: str = ""
    universal_caption: str = ""
    hashtag_matrix: HashtagMatrix = field(default_factory=HashtagMatrix)

    # Media
    image_prompt: str = ""
    image_urls: list[str] = field(default_factory=list)
    image_alt_text: str = ""
    video_url: str = ""

    # Platform-specific versions
    platform_contents: dict[str, PlatformContent] = field(default_factory=dict)

    # Metadata
    content_type: ContentType = ContentType.ORIGINAL
    content_hash: str = ""          # Dedup hash
    transform_score: float = 0.0    # 0-1 (must be â‰¥0.70)
    word_count: int = 0
    
    # Micro-niche caption for image/video overlay
    micro_caption: str = ""


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Agent Output Models
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

@dataclass
class ComplianceCheck:
    """Output from Platform Compliance Agent"""
    platform: str
    is_compliant: bool
    violations: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    adjusted_content: Optional[PlatformContent] = None


@dataclass
class RightsCheck:
    """Output from Rights & Safety Agent"""
    is_safe: bool
    source_verified: bool
    brand_safety_pass: bool
    pii_detected: bool = False
    watermark_detected: bool = False
    celeb_voice_detected: bool = False
    flags: list[str] = field(default_factory=list)


@dataclass
class RiskAssessment:
    """Output from Risk & Health Agent"""
    risk_score: int = 0             # 0-12 scale
    risk_level: RiskLevel = RiskLevel.LOW
    duplicate_score: float = 0.0    # 0-1
    account_health: dict = field(default_factory=dict)
    ban_risk: str = "low"
    recommendations: list[str] = field(default_factory=list)


@dataclass
class CostEstimate:
    """Output from Cost Agent"""
    tokens_used: int = 0
    latency_ms: float = 0
    tool_calls: int = 0
    cost_usd: float = 0.0
    budget_remaining_percent: float = 100.0
    recommended_model: str = "gpt-4.1-mini"
    budget_tier: str = "healthy"


@dataclass
class ReconcileDecision:
    """Output from ReconcileGPT"""
    should_publish: bool = False
    publish_mode: PublishMode = PublishMode.DRAFT
    confidence: float = 0.0
    risk_score: int = 0
    trade_off_summary: str = ""
    warnings: list[str] = field(default_factory=list)
    recommended_platforms: list[str] = field(default_factory=list)
    flagged_content: list[str] = field(default_factory=list)
    human_review_required: bool = True


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Queue & Publishing Models
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

@dataclass
class QueueItem:
    """Item in the publishing queue"""
    id: str
    content_pack_id: str
    platform: str
    platform_content: Optional[Any] = None
    scheduled_at: Optional[datetime] = None
    status: str = "pending"         # pending | scheduled | published | failed | dead_letter
    retry_count: int = 0
    max_retries: int = 3
    error_message: str = ""
    published_at: Optional[datetime] = None
    post_url: str = ""
    idempotency_key: str = ""
    content_hash: str = ""
    priority: int = 5


@dataclass
class PublishResult:
    """Result of publishing attempt"""
    queue_item_id: str
    platform: str
    success: bool
    post_url: str = ""
    post_id: str = ""
    error: str = ""
    published_at: Optional[datetime] = None
    engagement_initial: dict = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)

    @property
    def error_message(self) -> str:
        """Backward-compatible alias"""
        return self.error


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Monitoring Models
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

@dataclass
class EngagementMetrics:
    """Engagement tracking per post"""
    post_id: str
    platform: str
    views: int = 0
    likes: int = 0
    comments: int = 0
    shares: int = 0
    views_per_hour: float = 0.0
    retention_rate: float = 0.0
    ctr: float = 0.0
    measured_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class AccountHealth:
    """Account health status (multi-account aware)"""
    platform: str
    account_id: str = ""
    is_restricted: bool = False
    restriction_type: str = ""
    reach_trend_7d: float = 0.0     # Positive = growing, negative = declining
    error_rate_24h: float = 0.0
    last_successful_post: Optional[datetime] = None
    flags: list[str] = field(default_factory=list)
    # Multi-account tracking
    followers: int = 0
    engagement_rate: float = 0.0
    warning_count: int = 0
    is_flagged: bool = False
    is_shadow_banned: bool = False
    last_checked: Optional[datetime] = None


@dataclass
class AuditLogEntry:
    """Audit log entry for compliance"""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    agent_name: str = ""
    action_type: str = ""
    platform: str = ""
    content_hash: str = ""
    risk_score: int = 0
    human_approved: Optional[bool] = None
    result_status: str = ""
    error_details: str = ""
    metadata: dict = field(default_factory=dict)

