"""
Spawn Agent
===========
Module to spawn (create) new agents using LLM.
The meta-agent uses this to create child agents.
"""

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any

from agent_factory import get_factory, get_auto_spawn_config, GENERATED_DIR
from llm_client import get_llm_client


# Template for generating agents
AGENT_TEMPLATE = '''"""
Auto-generated agent: {agent_name}
Created: {timestamp}
Purpose: {purpose}
"""

from agents.base_agent import TaskAgent
from typing import Dict, Any


class {class_name}(TaskAgent):
    """
    {description}

    Auto-generated by spawn_agent.
    """

    def __init__(self):
        super().__init__(
            name="{agent_name}",
            description="{description}"
        )
        # Set safety paths
        self.allowed_paths = {allowed_paths}
        self.forbidden_paths = {forbidden_paths}

    def run(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the agent's task.

        Context contains:
        - business_background: Why this task exists
        - goal: What to achieve
        - input: Input files/data
        - output: Expected output
        """
        try:
            # TODO: Implement task logic here
            # This is a placeholder - LLM will fill in actual logic

            result = {{
                "status": "success",
                "message": f"{{self.name}} completed task",
                "data": {{}}
            }}

            return result

        except Exception as e:
            return {{
                "status": "failure",
                "message": f"{{self.name}} failed: {{str(e)}}",
                "error": str(e)
            }}
'''


def sanitize_class_name(name: str) -> str:
    """Convert a name to a valid Python class name."""
    # Remove special characters
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # Capitalize words
    words = clean.split("_")
    capitalized = "".join(word.capitalize() for word in words if word)
    # Ensure starts with letter
    if capitalized and not capitalized[0].isalpha():
        capitalized = "Agent" + capitalized
    return capitalized + "Agent" if not capitalized.endswith("Agent") else capitalized


def sanitize_file_name(name: str) -> str:
    """Convert a name to a valid file name."""
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower())
    return clean


def spawn_agent_from_template(
    name: str,
    purpose: str,
    description: str = "",
    allowed_paths: list = None,
    forbidden_paths: list = None,
) -> Optional[Path]:
    """
    Create a new agent using the template (no LLM).

    Args:
        name: Name for the new agent
        purpose: What the agent should do
        description: Detailed description
        allowed_paths: Paths the agent can modify
        forbidden_paths: Paths the agent cannot touch

    Returns:
        Path to the created file or None if failed
    """
    factory = get_factory()

    # Check if we can spawn more
    if not factory.can_spawn_more():
        print(f"[SPAWN] Cannot spawn more agents (limit reached)")
        return None

    # Get defaults from safety config
    if allowed_paths is None:
        allowed_paths = factory.safety.get("allowed_paths", [])
    if forbidden_paths is None:
        forbidden_paths = factory.safety.get("forbidden_paths", [])

    # Generate names
    class_name = sanitize_class_name(name)
    file_name = sanitize_file_name(name)
    timestamp = datetime.utcnow().isoformat()

    # Fill template
    code = AGENT_TEMPLATE.format(
        agent_name=name,
        class_name=class_name,
        timestamp=timestamp,
        purpose=purpose,
        description=description or purpose,
        allowed_paths=repr(allowed_paths),
        forbidden_paths=repr(forbidden_paths),
    )

    # Write file
    file_path = GENERATED_DIR / f"{file_name}.py"

    try:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        file_path.write_text(code, encoding="utf-8")
        print(f"[SPAWN] Created agent: {class_name} -> {file_path}")
        return file_path
    except Exception as e:
        print(f"[SPAWN] Failed to create agent: {e}")
        return None


def spawn_agent_with_llm(
    name: str, purpose: str, task_description: str, context: Dict[str, Any] = None
) -> Optional[Path]:
    """
    Create a new agent using LLM to generate the implementation.

    Args:
        name: Name for the new agent
        purpose: What the agent should do
        task_description: Detailed task description for LLM
        context: Additional context (allowed paths, etc.)

    Returns:
        Path to the created file or None if failed
    """
    factory = get_factory()
    llm = get_llm_client()

    # Check if we can spawn more
    if not factory.can_spawn_more():
        print(f"[SPAWN] Cannot spawn more agents (limit reached)")
        return None

    # Check if LLM is available
    if not llm.is_available():
        print(f"[SPAWN] LLM not available, using template fallback")
        return spawn_agent_from_template(name, purpose)

    # Build prompt for LLM
    class_name = sanitize_class_name(name)
    allowed_paths = factory.safety.get("allowed_paths", [])
    forbidden_paths = factory.safety.get("forbidden_paths", [])

    prompt = f"""Generate a Python agent class with the following requirements:

Agent Name: {name}
Class Name: {class_name}
Purpose: {purpose}

Task Description:
{task_description}

Requirements:
1. Inherit from TaskAgent (from agents.base_agent import TaskAgent)
2. Implement the run(self, context: Dict[str, Any]) method
3. Return a dict with "status", "message", and optionally "data"
4. Use self.safe_write(path, content) for any file writes
5. Allowed paths: {allowed_paths}
6. Forbidden paths: {forbidden_paths}

The agent should be safe, handle errors gracefully, and log its actions.

Generate ONLY the Python code, no explanations."""

    # Generate code
    code = llm.generate_code(prompt)

    if not code:
        print(f"[SPAWN] LLM failed to generate code, using template")
        return spawn_agent_from_template(name, purpose)

    # Review code for safety
    review = llm.review_code(code)
    if not review.get("is_safe", True):
        print(f"[SPAWN] Generated code flagged as unsafe: {review.get('issues')}")
        # Try to fix
        if review.get("issues"):
            fixed = llm.fix_code(code, str(review["issues"]))
            if fixed:
                code = fixed
            else:
                print(f"[SPAWN] Could not fix code, using template")
                return spawn_agent_from_template(name, purpose)

    # Write file
    file_name = sanitize_file_name(name)
    file_path = GENERATED_DIR / f"{file_name}.py"

    try:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        file_path.write_text(code, encoding="utf-8")
        print(f"[SPAWN] Created agent with LLM: {class_name} -> {file_path}")
        return file_path
    except Exception as e:
        print(f"[SPAWN] Failed to create agent: {e}")
        return None


def spawn_child_agent() -> Optional[Path]:
    """
    Spawn a child agent based on auto_spawn config.
    Called by the meta-agent during each run.

    Returns:
        Path to created agent or None
    """
    spawn_config = get_auto_spawn_config()

    if not spawn_config.get("enabled", False):
        print(f"[SPAWN] Auto-spawn is disabled")
        return None

    factory = get_factory()

    if not factory.can_spawn_more():
        print(f"[SPAWN] Agent limit reached")
        return None

    # Check triggers
    triggers = spawn_config.get("triggers", [])

    for trigger in triggers:
        trigger_type = trigger.get("type")

        if trigger_type == "new_job_type":
            # Check if there are jobs without matching agents
            # For now, skip - would need to compare jobs vs agents
            pass

        elif trigger_type == "performance_issue":
            # Check for slow tasks
            # For now, skip - would need performance data
            pass

        elif trigger_type == "error_pattern":
            # Check for repeated errors
            # For now, skip - would need error logs
            pass

    # For demo: create a sample agent if none exist
    if factory.count_generated_agents() == 0:
        print(f"[SPAWN] Creating initial demo agent")
        return spawn_agent_from_template(
            name="demo-agent",
            purpose="Demo agent to test the spawning system",
            description="A simple demo agent that logs a message",
        )

    return None
